Improvement 1939 add multi sort support to
conpagoaus/mongo-cursor-pagination pull request #4
Opened 2023-07-31 05:42 UTC by ashley-conpago

#### Changes Made

- allows paginated query with array of paginated fields using the new `findMulti` method
```
    const result = await Message.findMulti({
      paginatedFields: [
        { paginatedField: 'user_id', sortAscending: false },
        { paginatedField: 'created_at', sortAscending: false },
      ],
    })
    
    // user1 message1
    // user1 message2
    // user2 message1
    // user2 message2
```
- fixes sorts on the original `find` (`paginate`) function as well so now case insensitivity must be specified

#### Potential Risks
- small change to `paginate` function may mean that results will be returned in a different order than they were before

2023-07-31 06:10 UTC, ashley-conpago commented on src/config.ts
> +  COLLATION: undefined as CollationOptions | undefined,
had to change this to make it behave the same way as the backend repo, we may want to actually change this back and change the backend repo because I cant really see this case being desired often, (usually when you want something alphabetical you just want it alphabetical)

i.e. `H` will be sorted above `a` unless you do a case insensitive find

2023-07-31 06:51 UTC, emanuelet approved these changes
looks good. Could you rename the function to `paginateMulti` tho?

2023-08-01 04:07 UTC, danthistle-dev approved these changes

2023-08-01 04:32 UTC, tfxlong requested changes
Few comments to consider - I'll come back to this PR after those... maybe a test with 20 users or something where each pagination falls into values where duplicate users `Mary Smith` etc have to be sorted, and throw in pagination tests for single entry / first name + last name / first name + last name + age ?

2023-08-01 04:32 UTC, tfxlong commented on src/utils/query.ts
> +  const cursors: Array<FalsyOrAsc | FalsyOrDesc | TruthyOr> = []; // TODO: may want these as one big OR?
So I'd be interested in the handling of this one.... because if it was an $or (as appears cursors becomes) then I think we run into problems.... maybe 😄 Insofar as I can see, we are iterating every field we are paginating by ?

Sort by first then last name
```
Frances Peach
Greg Berry
John Banana
Kevin Mango
Lucky Apples
Mary Tangerine
```
If first pagination returns up to John, then we don't want to get all the values above `Berry` (as it would return user `Berry` again) and we can't use `$and` else it won't return `Apples`

I think we need to do a recursive function (or similar) to create an entry like this: 

```
$or: 
   field 1 = gt paginatedField1
   field 1 = eq pagainatedField1 + 
                 $or: 
                      field2 = gt paginatedField2 
                      field2 = eq paginatedField2 + 
                                    $or: 
                                          ...until no more fields and THEN _id

2023-08-02 03:50 UTC, ashley-conpago commented on src/utils/query.ts
> +  const cursors: Array<FalsyOrAsc | FalsyOrDesc | TruthyOr> = []; // TODO: may want these as one big OR?
resolved in https://github.com/conpagoaus/mongo-cursor-pagination/pull/4/commits/d35acb2b4622f062beaa9c2bb89fef760e7c8afa

2023-08-02 03:50 UTC, ashley-conpago commented on src/findMulti.ts
> +  // TODO: refactor this to handle a multiple sort
resolved in https://github.com/conpagoaus/mongo-cursor-pagination/pull/4/commits/d35acb2b4622f062beaa9c2bb89fef760e7c8afa

2023-08-02 03:52 UTC, ashley-conpago commented on src/utils/query.ts
> +      params.paginatedFields.length === 1 && params.paginatedFields[0].paginatedField == '_id';
resolved in https://github.com/conpagoaus/mongo-cursor-pagination/pull/4/commits/d5959ba6a360b505747b9140253258b1e787a67b

2023-08-03 02:49 UTC, tfxlong requested changes
Thanks for the discussion on this ! 😄 Few comments added, plus perhaps
1. _id should always be added as a final field 
2. _id should also flip from `asc` to `desc` if the pagination direction changes (if user was to try to change pagination direction of only one field, expectation would be that pagination restarts)
3. A test to mimic this case of paginate forwards then paginate backwards, when the same named user is caught in the middle of the pages (so is only finally sorted by the _id).

2023-08-03 03:54 UTC, ashley-conpago commented on src/utils/query.ts
> +): string {
I use the object args when there's a ton of optional args usually but for just 3 args I wouldn't bother

2023-08-03 03:57 UTC, ashley-conpago commented on src/utils/query.ts
> +  return Object.assign({}, ...sortArgs.map((f) => generateSort(f)));
offline conversation:
I think we talked about this, but that's what this was actually doing

2023-08-03 03:58 UTC, ashley-conpago commented on src/utils/query.ts
> + * ```
just installed my old spellcheck extension lel

2023-08-03 05:07 UTC, ashley-conpago commented on src/utils/query.ts
> +  })();
resolved in https://github.com/conpagoaus/mongo-cursor-pagination/pull/4/commits/abfb76b86d69341064f2ec64048cda074728a09e

2023-08-03 05:07 UTC, ashley-conpago commented on src/utils/query.ts
> +  if (onlyId) return { _id: { $gt: cursor } }; // TODO: check that cursor in this case will be _id and not object
resolved in https://github.com/conpagoaus/mongo-cursor-pagination/pull/4/commits/abfb76b86d69341064f2ec64048cda074728a09e

2023-08-04 01:44 UTC, emanuelet approved these changes

2023-08-04 01:48 UTC, tfxlong approved these changes
Looking good - nice test coverage too 😄 Re-comment on option to drop the `shouldSecondarySortOnId` to simplify params of function (and we will always sort by _id at the end of any others).

If wanting to keep, could rename to `shouldFinallySortOnId` given there could be more than one other field to paginate by.

But 🤷 😄

2023-08-04 01:48 UTC, tfxlong commented on src/utils/query.ts
> +   */
Nice 😄

2023-08-04 01:48 UTC, tfxlong commented on src/utils/query.ts
> +    );
Object argument ? ( 4 params 😄 🤷‍♂️ )

2023-08-04 01:48 UTC, tfxlong commented on test/sanitize.test.ts
> +  it('sanitizie and sanitizeMulti do the same thing given the same arguments', async () => {
*sanitizie 😄

2023-08-04 02:37 UTC, ashley-conpago commented on src/utils/query.ts
> +    );
resolved in https://github.com/conpagoaus/mongo-cursor-pagination/pull/4/commits/50b6953471ec3f6cba0d68624cd375b3814743f8

2023-08-04 03:51 UTC, ashley-conpago commented on test/sanitize.test.ts
> +  it('sanitizie and sanitizeMulti do the same thing given the same arguments', async () => {
resolved in https://github.com/conpagoaus/mongo-cursor-pagination/pull/4/commits/4db5f8e6df4f2a0537afb84797b7a84c4ade1019

2023-08-04 03:52 UTC, merged